// @ts-ignore — generated by the OpenNext build.
import handler from "./.open-next/worker.js";

export { CommunityStore } from "./src/worker/community-store";

export default {
  fetch: handler.fetch,
} satisfies ExportedHandler<CloudflareEnv>;
